name: Docker CI Build and Push

on:
  push:
    tags:
      - 'v*.*.*'
    

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 3. Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/elden-cake
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ endsWith(github.ref, '0.0') }}

      - name: 4. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 5. Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./web-content/
          push: true 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  redeploy:
    runs-on: ubuntu-18.04
    needs: [build_and_push_image]
    steps:
      - name: Deploy docker container webhook
        uses: CoyRy/webhook-action@master
        env:
          WEBHOOK_URL: http://${{ secrets.EC2_PUBLIC_IP }}:9000/hooks/elden-cake-deploy

          data: '{ "secret": "${{ secrets.WEBHOOK_SECRET }}", "repository": "${{ github.repository }}" }'

          HEADERS: '{"Content-Type": "application/json"}'
